MINIKLEXI = "data/miniklexi_corpus.txt"
KLEXIKON = "data/klexi_corpus.txt"
WIKI = "data/wiki_corpus.txt"
TOKEN_FREQ = "generated_tables/token_freq_table.json"
DISCOURSE_MARKER = "generated_tables/discourse_markers.json"
DISCOURSE_MARKER_WITH_SENSE = "generated_tables/discourse_markers_with_sense.json"
ALL_DISCOURSE_MARKER = "generated_tables/all_discourse_marker_senses.json"
